name: Publish

on: 
  push:
    branches: [ master ]

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # 👇 Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
        working-directory: website
      - name: Build
        run: yarn build
        working-directory: website
        # 👆 Build steps
      - uses: actions/upload-artifact@v3
        with:
          name: page
          path: website/build/irma-documentation
          if-no-files-found: error
          
  deploy:
    needs: build
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # 👇 Specify build output path
          path: . #website/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
